### ISSUE TITLE
pre-norm bug in transformer block

### ISSUE THREAD

**Issue by Howuhh** [Howuhh/faster-trajectory-transformer#3]
Pre-norm should be (as in [mingpt](https://github.com/karpathy/minGPT/blob/3ed14b2cec0dfdad3f4b2831f2b4a86d11aef150/mingpt/model.py#L97) code):
`x + attn(norm(x))`

In my code now:
```
norm_x = norm(x)
norm_x + attn(norm_x)
```
https://github.com/Howuhh/faster-trajectory-transformer/blob/cc1af3a7dfcd8ecc6d0ec0f719b7673329ec0c8b/trajectory/models/gpt/gpt.py#L32

While it is a small bug, I think it can have a great impact on performance and should be fixed. But it will break all pretrained checkpoints and I don't have time to retrain them for now.

**Comment by KornbergFresnel** [comment]
but i think you've implemented `x + attn(norm(x))` here, right?
https://github.com/Howuhh/faster-trajectory-transformer/blob/cc1af3a7dfcd8ecc6d0ec0f719b7673329ec0c8b/trajectory/models/gpt/gpt.py#L46

**Comment by Howuhh** [comment]
@KornbergFresnel the problem is here, `x` should be raw input, while in my code it is `x` after layer normalization. This norm should be applied only to Q, K, V, not residual. 
https://github.com/Howuhh/faster-trajectory-transformer/blob/cc1af3a7dfcd8ecc6d0ec0f719b7673329ec0c8b/trajectory/models/gpt/gpt.py#L32
Really easy to fix tho. You can fix it in your fork if it is needed. I will fix it too, but a bit later.
