### ISSUE TITLE
Jax Code

### ISSUE THREAD

**Issue by sglucas** [Howuhh/faster-trajectory-transformer#5]
Hi,

Thank you very much for your contribution.

I would like to ask is it possible to release the code based on Jax

Best

**Comment by Howuhh** [comment]
Hi! This code provided as is for now and I don't have plans for future maintenance, so rewriting it on jax is not my priority at the moment. My research interests are also shifting, so TT is not that interesting to me anymore. 

If I would write it on jax tho, I would start from this repo code as a reasonable base: https://github.com/jenkspt/gpt-jax
