### ISSUE TITLE
q,k,v linear layers

### ISSUE THREAD

**Issue by wj210** [Howuhh/faster-trajectory-transformer#6]
Hi, can i ask why is the q,k,v used as the input itself instead of passing through a linear layer? 
Comparing to the original code, this seems to be different.
Thanks!

**Comment by Howuhh** [comment]
Hi @wj210! In the original code self-attention is implemented manually, while I am using `torch.nn.MultiheadAttention` as it is more convenient and can be accelerated with new PyTorch versions (see new flash-attention in torch 2.0 for example).

The linear layers are just hidden inside the `torch.nn.MultiheadAttention`, you can look at documentation: https://pytorch.org/docs/stable/generated/torch.nn.MultiheadAttention.html. Input x will be transformed to q,k,v with different linear projections each.

**Comment by wj210** [comment]
i see now, thanks!
