### ISSUE TITLE
training input and target

### ISSUE THREAD

**Issue by wj210** [Howuhh/faster-trajectory-transformer#7]
Hi, I have another question regarding the training input and target.
Why is the training input x sliced from the flattened tensor? what I'm getting is that the input x is removing the value from last step of the sequence length while the target y is removing the 1st dimension of obs in the 1st step? shouldn't the training inputs be sliced along the seq_len rather than flattening everything and only taking out 1 token?
In the code below, shouldn't we not reshape and slice it.

`joined_discrete = self.discretizer.encode(joined).reshape(-1).astype(np.long)
        loss_pad_mask = loss_pad_mask.reshape(-1)
        return joined_discrete[:-1], joined_discrete[1:], loss_pad_mask[:-1]`

**Comment by Howuhh** [comment]
Hi! As this is the code in __getitem__ of the dataset, it only operates on [seq_len, ...] shapes, i.e. unbatched sequences

**Comment by wj210** [comment]
Yes, but however the slicing is done after flattening the seq_len together with the token dims so effectively we only slide it by 1 token? Instead of 1 entire timestep worth of tokens

**Comment by Howuhh** [comment]
@wj210 But that's the point! We discretize each domain such as states, actions, reward, then concatenate it to the one sequence and then flatten it (see architecture figure in the original paper). Thus, our task is to predict next token (not entire next timestamp!). 
For example, we will predict from token 0 of trajectory 0 ($s_0^0$) next token 1 of trajectory 0 ($s_0^1$), which is just next state dimension. Actual sequence length for the transformer is seq_len * (state_dim + action_dim + 1 for return to go)

**Comment by wj210** [comment]
Right, yes i guess i was just confused about that... Thanks again!
