### ISSUE TITLE
possible issue with rewards to go?

### ISSUE THREAD

**Issue by grahamannett** [Howuhh/faster-trajectory-transformer#9]
https://github.com/Howuhh/faster-trajectory-transformer/blob/6621fc9e192f472b901863bf91dd452d6639e61c/trajectory/datasets/d4rl_dataset.py#L25

Hi, I have been using this repo for some experiments and was digging into some parts of it and was wondering is this correct?  These values don't seem to match up with what I see for the sample trajectory off of https://github.com/jannerm/trajectory-transformer/blob/8834a6ed04ceeab8fdb9465e145c6e041c05d71b/trajectory/datasets/sequence.py#L97

There is also a high likelihood I am wrong but the rewards to go for me seem like they are much bigger than I would expect.  If so its possible this line is just supposed to be `(rewards[t + 1 :].T @ discounts[: -t - 1])` (which for me then matches up with the original repo RTG values) but I am not certain if I am understanding everything correctly.  

For comparing values on halfcheetah-medium-v2 the rtg on the first trajectory using your calculation:

```
(Pdb) values.sum()
242487360.0
```

while on the original repo:

```
(Pdb) self.values_segmented[0].sum()
432073.4913363826
```

**Comment by Howuhh** [comment]
Hi @grahamannett! Indeed, seems like this is a bug from incorrect numpy broadcasting which I missed unfortunately 😞. You can correct it with .squeeze(), .T or just [t + 1:, 0]. It's amazing that it trained so nicely in spite of this!

**Comment by Howuhh** [comment]
Also, @grahamannett, if you use gpt in your code, pay attention to the existing bug from https://github.com/Howuhh/faster-trajectory-transformer/pull/4 which is not merged yet.

**Comment by grahamannett** [comment]
thanks for the heads up.  its probably worth offering @Howuhh would you like me to retrain the models for the checkpoints with that fix?  I am using the models to benchmark against anyway and will probably retrain them since i did not have that pre-norm fix.

**Comment by Howuhh** [comment]
@grahamannett yeah, that would be really cool, as I'm mostly busy with other things that have nothing to do with the TT at the moment. You can make a separate PR for this (or whatever you feel more comfortable with)

**Comment by grahamannett** [comment]
@Howuhh damn, i originally had forked your repo and am using it too much/in process of running a fair amount of experiments and dont want to mess with what i have.  seems like i cant make a new fork until i detach my current project from yours and requires submitting a github support ticket.  i kicked off the runs that you have listed with the fix though and will PR once I get the fork issue sorted out.  thanks a lot for the codebase, was very helpful!

**Comment by Howuhh** [comment]
@grahamannett It's okay, do as you please. My project for which I wrote this code failed, glad the code is useful to someone anyway
